version: "3.8"

services:
  node_backend:
    container_name: node_backend
    build: .
    command: npm run dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    
volumes:
  pg_data: